### ISSUE TITLE
 500 Unhandled internal error: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by neuroverflow** [slayer/ftpserver#4]
Hi (and thank you for that great tool!)

I get an error 500 when trying to connect telegram

```
curl -v -T kitty.jpg ftp://telegram:telegram@localhost:2121/
*   Trying 127.0.0.1:2121...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (127.0.0.1) port 2121 (#0)
< 220 ftpserver
> USER telegram
< 331 OK
> PASS telegram
< 500 Unhandled internal error: runtime error: invalid memory address or nil pointer dereference
* Access denied: 500
```

my docker file: 

```
  ftp2telegram:
    container_name: ftp2telegram
    image: fclairamb/ftpserver
    restart: unless-stopped
    ports:
      - '2121-2130:2121-2130'
    volumes:
      - /home/neuro/Docker/ftp2telegram:/tmp
      - /home/neuro/Docker/ftp2telegram_cfg:/app
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris

```

my ftpserver.json:
notice that cert.pm and key.pm are in my folder /app

```
{
  "version": 1,
  "accesses": [
    {
      "fs": "telegram",
      "shared": true,
      "user": "telegram",
      "pass": "telegram",
      "params": {
        "Token": "fghgfh:fghgfhfgh",
        "ChatID": "fghgfh"}
    }
  ],
  "passive_transfer_port_range": {
    "start": 2122,
    "end": 2130
  },
   "tls": {
      "server_cert": {
         "cert": "cert.pem",
         "key": "key.pem"
      }
   }
}
```
